In [1]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense,InputLayer

In [11]:
import pandas as pd
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

#Model Building

In [3]:
model = Sequential()

# InputLayer
model.add(InputLayer(shape=(2,)))

# Hidden Layers
model.add(Dense(2, activation='linear'))

# output Layer
model.add(Dense(1, activation='linear'))

In [4]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
model.get_weights()

[array([[-0.88923967,  0.47789216],
        [-0.7873783 ,  0.11670971]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.13944602],
        [-0.2282275 ]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
import numpy as np
new_weights = [
    np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
    np.array([0,0],dtype=np.float32),
    np.array([[0.1],[0.1]],dtype=np.float32),
    np.array([0],dtype=np.float32)
    ]
new_weights

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [12]:
model.fit(df.iloc[:,:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 19.0021 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.0784 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.4028 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.5570 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.2607 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.3043
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 19.1345
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.7855
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 18.0691 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 15.2315
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.1239 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 13.8858
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 11.2984
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14.2960 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.5561
Epoch 16/75
4/4 ━━━━━━

In [13]:
model.get_weights()

[array([[-1.0828406 ,  0.34895477],
        [-0.986766  , -0.01392481]], dtype=float32),
 array([-0.19942936, -0.13149643], dtype=float32),
 array([[-0.31272978],
        [-0.09754006]], dtype=float32),
 array([0.16393949], dtype=float32)]