In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


# Scalar or Zero Dim Tensor

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


# One Dimensional Tensor

In [ ]:
tensor_one_d_int = tf.constant([2,3,4,5])
print(tensor_one_d_int)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
tensor_one_d_float = tf.constant([2,3,4,5.])
print(tensor_one_d_float)

tf.Tensor([2. 3. 4. 5.], shape=(4,), dtype=float32)


In [ ]:
tensor_one_d_float = tf.constant([2,3,4,5],dtype=tf.float32)
print(tensor_one_d_float)

tf.Tensor([2. 3. 4. 5.], shape=(4,), dtype=float32)


# Type Casting

In [ ]:
int_type_casted_tensor = tf.cast(tensor_one_d_float,dtype=tf.int32)
bool_type_casted_tensor = tf.cast(tensor_one_d_float,dtype=tf.bool)
print(int_type_casted_tensor)
print(bool_type_casted_tensor)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)
tf.Tensor([ True  True  True  True], shape=(4,), dtype=bool)


# Two Dimensional Tensor

In [ ]:
tensor_two_d = tf.constant([[2,3,4,5],[2,3,4,5]])
print(tensor_two_d)

tf.Tensor(
[[2 3 4 5]
 [2 3 4 5]], shape=(2, 4), dtype=int32)


# Three Dimensional Tensor

In [ ]:
tensor_three_d = tf.constant([[[2,3,4,5],[2,3,4,5]],[[2,3,4,5],[2,3,4,5]]])
print(tensor_three_d)

tf.Tensor(
[[[2 3 4 5]
  [2 3 4 5]]

 [[2 3 4 5]
  [2 3 4 5]]], shape=(2, 2, 4), dtype=int32)


# Four Dimensional Tensor

In [ ]:
tensor_four_d = tf.constant([[[[2,3,4,5],[2,3,4,5]],[[2,3,4,5],[2,3,4,5]]],[[[2,3,4,5],[2,3,4,5]],[[2,3,4,5],[2,3,4,5]]],[[[2,3,4,5],[2,3,4,5]],[[2,3,4,5],[2,3,4,5]]]])
print(tensor_four_d)

tf.Tensor(
[[[[2 3 4 5]
   [2 3 4 5]]

  [[2 3 4 5]
   [2 3 4 5]]]


 [[[2 3 4 5]
   [2 3 4 5]]

  [[2 3 4 5]
   [2 3 4 5]]]


 [[[2 3 4 5]
   [2 3 4 5]]

  [[2 3 4 5]
   [2 3 4 5]]]], shape=(3, 2, 2, 4), dtype=int32)


In [ ]:
one_d = tensor_one_d_int.shape
two_d = tensor_two_d.shape
three_d = tensor_three_d.shape
four_d = tensor_four_d.shape

print("One Dimensional Tensor Shape: ",one_d)
print("Two Dimensional Tensor Shape:(no_of_one_d, one_d_shape)",two_d)
print("Three Dimensional Tensor Shape:(no_of_two_d, two_d_shape) ",three_d)
print("Four Dimensional Tensor Shape:(no_of_three_d, three_d_shape) ",four_d)

One Dimensional Tensor Shape:  (4,)
Two Dimensional Tensor Shape:(no_of_one_d, one_d_shape) (2, 4)
Three Dimensional Tensor Shape:(no_of_two_d, two_d_shape)  (2, 2, 4)
Four Dimensional Tensor Shape:(no_of_three_d, three_d_shape)  (3, 2, 2, 4)


# Boolean and String Tensors

In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world","hi "])
print(tensor_string)

tf.Tensor([b'hello world' b'hi '], shape=(2,), dtype=string)


# Converting numpy array to tensors

In [ ]:
import numpy as np

In [ ]:
np_arr = np.array([1,2,3,4])
print(np_arr)

[1 2 3 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_arr)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


# [Eye](https://www.tensorflow.org/api_docs/python/tf/eye) - Constructs an Identity Matrix

In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=4,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape=(2, 3, 4), dtype=float32)


# [Fill Tensor](https://www.tensorflow.org/api_docs/python/tf/fill) - Creates a tensor filled with a scalar value.

In [ ]:
fill_tensor = tf.fill(
    [5,2,3], 6, name=None, layout=None
)
print(fill_tensor)

tf.Tensor(
[[[6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]]], shape=(5, 2, 3), dtype=int32)


#[Ones_like](https://www.tensorflow.org/api_docs/python/tf/ones_like) - Creates a tensor of all ones that has the same shape as the input.

In [ ]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]],dtype=tf.float32)
ones_like_tensor = tf.ones_like(tensor)
print(ones_like_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


# [zeros_like](https://www.tensorflow.org/api_docs/python/tf/zeros_like) - Creates a tensor with all elements set to zero.

In [ ]:
zeros_like_tensor = tf.zeros_like(tensor)
print(zeros_like_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# [Tensor Shape](https://www.tensorflow.org/api_docs/python/tf/shape)- Returns a tensor containing the shape of the input tensor.



In [ ]:
tf.shape(zeros_like_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

# [Rank of a Tensor](https://www.tensorflow.org/api_docs/python/tf/rank)

In [ ]:
tensor_rank = tf.rank(
    tensor_four_d
)
print(tensor_rank)

tf.Tensor(4, shape=(), dtype=int32)


# [Size of tensor](https://www.tensorflow.org/api_docs/python/tf/size)

In [ ]:
print(tf.size(tensor_one_d_int))
print(tf.size(tensor_two_d))


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


# [random_normal_initializer](https://www.tensorflow.org/api_docs/python/tf/random_normal_initializer) - Initializer that generates tensors with a normal distribution.

In [ ]:
random_normal_initializer_tensor = tf.random_normal_initializer(mean=0.0, stddev=1.0, seed=None
)
random_normal_initializer_tensor(shape=[2,3])

print(tf.constant(random_normal_initializer_tensor(shape=[2,3])))
print(tf.Variable(random_normal_initializer_tensor(shape=[2,3])))

tf.Tensor(
[[ 1.0573303  -0.41595986 -0.42625573]
 [-0.1411322   0.30207893  0.30895996]], shape=(2, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1.4087377 ,  0.77497876, -0.11998365],
       [ 0.25652277, -1.0472131 ,  0.67519414]], dtype=float32)>


# Set_seed - This is like random_state in Machine Learning

In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
